Repository Bastion-BaaS/bastion-cli, pull requests merged in 2022-03, with the labels that each got.

#1 Core functionality setup deploy
  .gitignore
  README.md
  package.json
  src/commands/deploy.js
  src/commands/destroy.js
  src/commands/setup.js
  src/prompts/deletePrompt.js
  src/prompts/getAppInfo.js
  src/utils/bastion.yaml
  src/utils/errorHandler.js
  src/utils/test.yaml
  src/utils/ui.js
Labels: Ready To Merge

#3 Added functionality to show status of app creation.
  src/commands/config.js
  src/commands/deploy.js
  src/commands/show.js
  src/prompts/deletePrompt.js
  src/prompts/getAppInfo.js
  src/prompts/getAppName.js
  src/utils/bastion.yaml
  src/utils/errorHandler.js
  src/utils/test.yaml
Labels: Ready To Merge

#4 Update README
  README.md
Labels: Needs review, Ready To Merge

#5 Add Roles and SGs of App and DB Servers to initial deployment file
  README.md
  src/utils/bastion.yaml
Labels: Work in Progress

#9 Add logo
  Bastion_logo.png
  README.md
  src/utils/logo.js
  src/utils/ui.js
Labels: Ready To Merge

#13 add colors and create a new logo
  .gitignore
  package-lock.json
  package.json
  src/prompts/getAppInfo.js
  src/utils/logo.js
  src/utils/ui.js
Labels: Ready To Merge

#14 Cloudformation fine tuning
  README.md
  package-lock.json
  package.json
  src/commands/deploy.js
  src/commands/show.js
  src/prompts/getAppInfo.js
  src/utils/bastion.yaml
  src/utils/credentials.js
  src/utils/errorHandler.js
  src/utils/ui.js
Labels: Ready To Merge
